apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  creationTimestamp: "2022-01-21T12:53:49Z"
  generation: 1
  name: osu-alltoall-3procs
  namespace: mpi-benchmark
  resourceVersion: "85093"
  uid: 29b2f4ef-33b7-4456-bad2-86a28cc7915c
spec:
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "3"
            - -bind-to
            - none
            - -map-by
            - slot
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - bash
            - -c
            - /opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/collective/osu_alltoall
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            imagePullPolicy: Always
            name: mpi-launcher
          initContainers:
          - command:
            - bash
            - -cx
            - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile
              is ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready
              ...''; sleep 10; exit 1) && while read host; do while ! ssh $host echo
              $host ; do date; echo "Pod $host is not up ..."; sleep 10; done; date;
              echo "Pod $host is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            name: wait-hostfilename
            volumeMounts:
            - mountPath: /etc/mpi
              name: mpi-job-config
            - mountPath: /root/.ssh
              name: ssh-auth
    Worker:
      replicas: 3
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
            imagePullPolicy: Always
            name: mpi-worker
            securityContext:
              privileged: true
          nodeSelector:
            node.kubernetes.io/instance-type: m5.xlarge
  slotsPerWorker: 1
status:
  completionTime: "2022-01-21T12:54:16Z"
  conditions:
  - lastTransitionTime: "2022-01-21T12:53:49Z"
    lastUpdateTime: "2022-01-21T12:53:49Z"
    message: MPIJob mpi-benchmark/osu-alltoall-3procs is created.
    reason: MPIJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2022-01-21T12:54:02Z"
    lastUpdateTime: "2022-01-21T12:54:02Z"
    message: MPIJob mpi-benchmark/osu-alltoall-3procs is running.
    reason: MPIJobRunning
    status: "False"
    type: Running
  - lastTransitionTime: "2022-01-21T12:54:16Z"
    lastUpdateTime: "2022-01-21T12:54:16Z"
    message: MPIJob mpi-benchmark/osu-alltoall-3procs successfully completed.
    reason: MPIJobSucceeded
    status: "True"
    type: Succeeded
  replicaStatuses:
    Launcher:
      succeeded: 1
    Worker: {}
  startTime: "2022-01-21T12:53:49Z"
