apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.131.8.75"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.131.8.75"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: anyuid
    creationTimestamp: "2022-01-25T11:39:38Z"
    generateName: osu-alltoall-2procs-launcher--1-
    labels:
      controller-uid: 84705710-d9e7-48e9-a6af-0204190b7a50
      job-name: osu-alltoall-2procs-launcher
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: launcher
      training.kubeflow.org/operator-name: mpi-operator
    name: osu-alltoall-2procs-launcher--1-pn24x
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: osu-alltoall-2procs-launcher
      uid: 84705710-d9e7-48e9-a6af-0204190b7a50
    resourceVersion: "212042"
    uid: c4a56072-d03e-4669-8311-c756879ef296
  spec:
    containers:
    - command:
      - mpirun
      - --allow-run-as-root
      - -np
      - "2"
      - -bind-to
      - none
      - -map-by
      - slot
      - -mca
      - pml
      - ob1
      - -mca
      - btl
      - ^openib
      - bash
      - -c
      - /opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/collective/osu_alltoall
      env:
      - name: K_MPI_JOB_ROLE
        value: launcher
      - name: OMPI_MCA_orte_keep_fqdn_hostnames
        value: "true"
      - name: OMPI_MCA_orte_default_hostfile
        value: /etc/mpi/hostfile
      - name: OMPI_MCA_plm_rsh_args
        value: -o ConnectionAttempts=10
      - name: OMPI_MCA_orte_set_default_slots
        value: "1"
      - name: NVIDIA_VISIBLE_DEVICES
      - name: NVIDIA_DRIVER_CAPABILITIES
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: Always
      name: mpi-launcher
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-hcvkk
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-launcher
    imagePullSecrets:
    - name: default-dockercfg-nchh4
    initContainers:
    - command:
      - bash
      - -cx
      - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile is
        ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready ...'';
        sleep 10; exit 1) && while read host; do while ! ssh $host echo $host ; do
        date; echo "Pod $host is not up ..."; sleep 10; done; date; echo "Pod $host
        is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: IfNotPresent
      name: wait-hostfilename
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-hcvkk
        readOnly: true
    nodeName: ip-10-0-144-156.eu-central-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: OnFailure
    schedulerName: default-scheduler
    securityContext:
      seLinuxOptions:
        level: s0:c26,c15
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - configMap:
        defaultMode: 420
        items:
        - key: hostfile
          mode: 292
          path: hostfile
        - key: discover_hosts.sh
          mode: 365
          path: discover_hosts.sh
        name: osu-alltoall-2procs-config
      name: mpi-job-config
    - name: kube-api-access-hcvkk
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:51Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:58Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:58Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:38Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://04c0bb9d98b2b2afe496db1d525c1350751e9bc82612dc341bd0d591b3181b06
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:557c456dfdd215e17c7ff15f89e13c128b523b0c75cb312c49585073e69131a0
      lastState: {}
      name: mpi-launcher
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://04c0bb9d98b2b2afe496db1d525c1350751e9bc82612dc341bd0d591b3181b06
          exitCode: 0
          finishedAt: "2022-01-25T11:39:57Z"
          reason: Completed
          startedAt: "2022-01-25T11:39:51Z"
    hostIP: 10.0.144.156
    initContainerStatuses:
    - containerID: cri-o://7f8c6c6475179cb2aecc3edc98e0fb171fcb35ffe5da6357377670cb73a969d6
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:557c456dfdd215e17c7ff15f89e13c128b523b0c75cb312c49585073e69131a0
      lastState: {}
      name: wait-hostfilename
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: cri-o://7f8c6c6475179cb2aecc3edc98e0fb171fcb35ffe5da6357377670cb73a969d6
          exitCode: 0
          finishedAt: "2022-01-25T11:39:50Z"
          reason: Completed
          startedAt: "2022-01-25T11:39:40Z"
    phase: Succeeded
    podIP: 10.131.8.75
    podIPs:
    - ip: 10.131.8.75
    qosClass: BestEffort
    startTime: "2022-01-25T11:39:38Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.131.30.25"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.131.30.25"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: privileged
    creationTimestamp: "2022-01-25T11:39:38Z"
    labels:
      app: osu-alltoall-2procs-worker
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "0"
    name: osu-alltoall-2procs-worker-0
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: 9e15dd95-94aa-4dd1-ab09-00a55ee73959
    resourceVersion: "211819"
    uid: d359be31-eadc-4df6-8631-2074336b262f
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-xcsv4
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-0
    imagePullSecrets:
    - name: default-dockercfg-nchh4
    nodeName: ip-10-0-145-75.eu-central-1.compute.internal
    nodeSelector:
      node.kubernetes.io/instance-type: c4.xlarge
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: osu-alltoall-2procs-worker
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-xcsv4
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:38Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:40Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:40Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:38Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://12a7f31635fdf982b70d5da2cd99b198448944f7d8a44bc1ebb0771a59449dd6
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:acae5e0344080fa4abbfa4c652208e9ece002f9199ae331154e3f224d7b80140
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-25T11:39:40Z"
    hostIP: 10.0.145.75
    phase: Running
    podIP: 10.131.30.25
    podIPs:
    - ip: 10.131.30.25
    qosClass: BestEffort
    startTime: "2022-01-25T11:39:38Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.128.16.57"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.128.16.57"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: privileged
    creationTimestamp: "2022-01-25T11:39:38Z"
    labels:
      app: osu-alltoall-2procs-worker
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "1"
    name: osu-alltoall-2procs-worker-1
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: 9e15dd95-94aa-4dd1-ab09-00a55ee73959
    resourceVersion: "211838"
    uid: 707ca382-8b78-4558-bfaa-0985cb32d429
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-89f9z
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-1
    imagePullSecrets:
    - name: default-dockercfg-nchh4
    nodeName: ip-10-0-147-160.eu-central-1.compute.internal
    nodeSelector:
      node.kubernetes.io/instance-type: c4.xlarge
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: osu-alltoall-2procs-worker
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-89f9z
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:38Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:41Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:41Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T11:39:38Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://1712bcfcc91b6ed492cf458b54fa81b7de24d26e4aeb1249498d9b072c35b5e4
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:acae5e0344080fa4abbfa4c652208e9ece002f9199ae331154e3f224d7b80140
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-25T11:39:41Z"
    hostIP: 10.0.147.160
    phase: Running
    podIP: 10.128.16.57
    podIPs:
    - ip: 10.128.16.57
    qosClass: BestEffort
    startTime: "2022-01-25T11:39:38Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
