apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.8.176"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.8.176"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: anyuid
  creationTimestamp: "2022-03-09T12:11:49Z"
  labels:
    job-name: ssd-training-2
    matrix-benchmarking: "true"
    runai-pod-job-mutated: "true"
  name: ssd-training-2
  namespace: matrix-benchmarking
  resourceVersion: "126482"
  uid: 7fafa83b-56cd-49ed-81e0-cc7122507279
spec:
  containers:
  - args:
    - |
      mkdir /tmp/cfg
      cp -v "$SRC_CONFIG_DIR"/* /tmp/cfg
      sed -i 's|/data/coco2017_tfrecords|'$STORAGE_DIR'/coco2017_tfrecords|' /tmp/cfg/*
      sed -i 's|/checkpoints|'$STORAGE_DIR'/checkpoints|' /tmp/cfg/*

      if [[ "training" == "inference" ]]; then
        count=0
        while true; do
          bash -x examples/SSD320_FP16_1GPU_BENCHMARK.sh /tmp/cfg --raport_file=/tmp/summary.json
          count=$(($count + 1))
          echo "INFERENCE_LOOP_COUNT=$count"
        done
      else
        RESULTS_DIR=/tmp/results
        mkdir "$RESULTS_DIR"
        bash -x examples/SSD320_FP16_1GPU_BENCHMARK.sh "$RESULTS_DIR" /tmp/cfg --raport_file=/tmp/summary.json
      fi
    command:
    - bash
    - -ceuxo
    - pipefail
    env:
    - name: SRC_CONFIG_DIR
      value: /workdir/models/research/configs/
    - name: STORAGE_DIR
      value: /storage
    - name: INFERENCE_TIME
    image: quay.io/openshift-psap/nvidiadl-ssd-training-benchmark:ssd
    imagePullPolicy: IfNotPresent
    name: cnt
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /storage/
      name: storage-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2f4nh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-sdpg9
  nodeName: ip-10-0-143-249.eu-central-1.compute.internal
  nodeSelector:
    node.kubernetes.io/instance-type: p3.2xlarge
    nvidia.com/gpu.present: "true"
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: benchmarking-coco-dataset
  - name: kube-api-access-2f4nh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-09T12:26:56Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-09T12:41:54Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-09T12:41:54Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-09T12:26:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://539114e37fab4124affc9f08eb4a367e3811d8ec65a1a0211d139ae2d3793264
    image: quay.io/openshift-psap/nvidiadl-ssd-training-benchmark:ssd
    imageID: quay.io/openshift-psap/nvidiadl-ssd-training-benchmark@sha256:0177e9f4174b98ed1b79a952b2bdf60be6c0a1d7d534b46e6f34a6012db4e52f
    lastState: {}
    name: cnt
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://539114e37fab4124affc9f08eb4a367e3811d8ec65a1a0211d139ae2d3793264
        exitCode: 0
        finishedAt: "2022-03-09T12:41:54Z"
        reason: Completed
        startedAt: "2022-03-09T12:26:59Z"
  hostIP: 10.0.143.249
  phase: Succeeded
  podIP: 10.129.8.176
  podIPs:
  - ip: 10.129.8.176
  qosClass: BestEffort
  startTime: "2022-03-09T12:26:56Z"
