apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.2.17"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.2.17"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: anyuid
    creationTimestamp: "2022-01-25T08:29:50Z"
    generateName: osu-alltoall-2procs-launcher--1-
    labels:
      controller-uid: 52fd5a8e-8230-4e20-a466-1908f4b0f055
      job-name: osu-alltoall-2procs-launcher
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: launcher
      training.kubeflow.org/operator-name: mpi-operator
    name: osu-alltoall-2procs-launcher--1-psfz8
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: osu-alltoall-2procs-launcher
      uid: 52fd5a8e-8230-4e20-a466-1908f4b0f055
    resourceVersion: "31225"
    uid: 3233d7db-dc1f-4da8-915c-b2dda520f8a7
  spec:
    containers:
    - command:
      - mpirun
      - --allow-run-as-root
      - -np
      - "2"
      - -bind-to
      - none
      - -map-by
      - slot
      - -mca
      - pml
      - ob1
      - -mca
      - btl
      - ^openib
      - bash
      - -c
      - /opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/collective/osu_alltoall
      env:
      - name: K_MPI_JOB_ROLE
        value: launcher
      - name: OMPI_MCA_orte_keep_fqdn_hostnames
        value: "true"
      - name: OMPI_MCA_orte_default_hostfile
        value: /etc/mpi/hostfile
      - name: OMPI_MCA_plm_rsh_args
        value: -o ConnectionAttempts=10
      - name: OMPI_MCA_orte_set_default_slots
        value: "1"
      - name: NVIDIA_VISIBLE_DEVICES
      - name: NVIDIA_DRIVER_CAPABILITIES
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: Always
      name: mpi-launcher
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-6b6dj
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-launcher
    imagePullSecrets:
    - name: default-dockercfg-nchh4
    initContainers:
    - command:
      - bash
      - -cx
      - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile is
        ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready ...'';
        sleep 10; exit 1) && while read host; do while ! ssh $host echo $host ; do
        date; echo "Pod $host is not up ..."; sleep 10; done; date; echo "Pod $host
        is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: IfNotPresent
      name: wait-hostfilename
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-6b6dj
        readOnly: true
    nodeName: ip-10-0-134-246.eu-central-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: OnFailure
    schedulerName: default-scheduler
    securityContext:
      seLinuxOptions:
        level: s0:c26,c15
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - configMap:
        defaultMode: 420
        items:
        - key: hostfile
          mode: 292
          path: hostfile
        - key: discover_hosts.sh
          mode: 365
          path: discover_hosts.sh
        name: osu-alltoall-2procs-config
      name: mpi-job-config
    - name: kube-api-access-6b6dj
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:30:03Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:30:10Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:30:10Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:50Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://24db28367a75934b43dcedf86347d79c088aefb2f0b1f8b5bcc05c5fdbcfaf59
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:557c456dfdd215e17c7ff15f89e13c128b523b0c75cb312c49585073e69131a0
      lastState: {}
      name: mpi-launcher
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://24db28367a75934b43dcedf86347d79c088aefb2f0b1f8b5bcc05c5fdbcfaf59
          exitCode: 0
          finishedAt: "2022-01-25T08:30:09Z"
          reason: Completed
          startedAt: "2022-01-25T08:30:03Z"
    hostIP: 10.0.134.246
    initContainerStatuses:
    - containerID: cri-o://d42168f8b77dbcfc3d9c11a7266a0a8379ea596f50adaa56bc7ed7fb681b00a0
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:557c456dfdd215e17c7ff15f89e13c128b523b0c75cb312c49585073e69131a0
      lastState: {}
      name: wait-hostfilename
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: cri-o://d42168f8b77dbcfc3d9c11a7266a0a8379ea596f50adaa56bc7ed7fb681b00a0
          exitCode: 0
          finishedAt: "2022-01-25T08:30:02Z"
          reason: Completed
          startedAt: "2022-01-25T08:29:52Z"
    phase: Succeeded
    podIP: 10.130.2.17
    podIPs:
    - ip: 10.130.2.17
    qosClass: BestEffort
    startTime: "2022-01-25T08:29:50Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.129.2.13"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.129.2.13"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: privileged
    creationTimestamp: "2022-01-25T08:29:50Z"
    labels:
      app: osu-alltoall-2procs-worker
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "0"
    name: osu-alltoall-2procs-worker-0
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: b5ad12c2-252e-43b8-8824-96a876eec9b9
    resourceVersion: "31118"
    uid: 422d96c3-a37c-4810-94cb-5525f9e1cda7
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-kc6gk
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-0
    imagePullSecrets:
    - name: default-dockercfg-nchh4
    nodeName: ip-10-0-148-13.eu-central-1.compute.internal
    nodeSelector:
      node.kubernetes.io/instance-type: c4.xlarge
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: osu-alltoall-2procs-worker
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-kc6gk
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:50Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:53Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:53Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:50Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://f0cc8a30c9babba802dbcfcc1c5179fa55a3dc7e0aa5e969e521232453ebd3f7
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:acae5e0344080fa4abbfa4c652208e9ece002f9199ae331154e3f224d7b80140
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-25T08:29:52Z"
    hostIP: 10.0.148.13
    phase: Running
    podIP: 10.129.2.13
    podIPs:
    - ip: 10.129.2.13
    qosClass: BestEffort
    startTime: "2022-01-25T08:29:50Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.2.16"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.2.16"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: privileged
    creationTimestamp: "2022-01-25T08:29:50Z"
    labels:
      app: osu-alltoall-2procs-worker
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "1"
    name: osu-alltoall-2procs-worker-1
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: b5ad12c2-252e-43b8-8824-96a876eec9b9
    resourceVersion: "31124"
    uid: 14d2e676-ff45-4534-ac23-45e3cf3ecd55
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-2l29h
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-1
    imagePullSecrets:
    - name: default-dockercfg-nchh4
    nodeName: ip-10-0-134-246.eu-central-1.compute.internal
    nodeSelector:
      node.kubernetes.io/instance-type: c4.xlarge
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: osu-alltoall-2procs-worker
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-2l29h
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:50Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:53Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:53Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-25T08:29:50Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://9f1750818ec978f8718d6a43c3983b4c3bd930699998bf3092b67f1b0f9fc22f
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:acae5e0344080fa4abbfa4c652208e9ece002f9199ae331154e3f224d7b80140
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-25T08:29:52Z"
    hostIP: 10.0.134.246
    phase: Running
    podIP: 10.130.2.16
    podIPs:
    - ip: 10.130.2.16
    qosClass: BestEffort
    startTime: "2022-01-25T08:29:50Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
