apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeflow.org/v2beta1","kind":"MPIJob","metadata":{"annotations":{},"name":"latency-2procs","namespace":"mpi-benchmark"},"spec":{"cleanPodPolicy":"Running","mpiReplicaSpecs":{"Launcher":{"replicas":1,"template":{"spec":{"containers":[{"command":["mpirun","--allow-run-as-root","-np","2","-bind-to","none","-map-by","slot","-mca","pml","ob1","-mca","btl","^openib","bash","-c","/opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency"],"image":"image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base","imagePullPolicy":"Always","name":"mpi-launcher"}],"initContainers":[{"command":["bash","-cx","[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] \u0026\u0026 (date; echo 'Hostfile is ready'; cat /etc/mpi/hostfile) || (date; echo 'Hostfile not ready ...'; sleep 10; exit 1) \u0026\u0026 while read host; do while ! ssh $host echo $host ; do date; echo \"Pod $host is not up ...\"; sleep 10; done; date; echo \"Pod $host is ready\"; done \u003c\u003c\u003c \"$(cat /etc/mpi/hostfile)\""],"image":"image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base","name":"wait-hostfilename","volumeMounts":[{"mountPath":"/etc/mpi","name":"mpi-job-config"},{"mountPath":"/root/.ssh","name":"ssh-auth"}]}]}}},"Worker":{"replicas":2,"template":{"spec":{"containers":[{"image":"image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench","imagePullPolicy":"Always","name":"mpi-worker","securityContext":{"privileged":true}}]}}}},"slotsPerWorker":1}}
  creationTimestamp: "2022-01-19T16:30:49Z"
  generation: 1
  name: latency-2procs
  namespace: mpi-benchmark
  resourceVersion: "129976"
  uid: 01c61d0e-c234-494a-9dd3-e15d9685c918
spec:
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "2"
            - -bind-to
            - none
            - -map-by
            - slot
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - bash
            - -c
            - /opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            imagePullPolicy: Always
            name: mpi-launcher
          initContainers:
          - command:
            - bash
            - -cx
            - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile
              is ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready
              ...''; sleep 10; exit 1) && while read host; do while ! ssh $host echo
              $host ; do date; echo "Pod $host is not up ..."; sleep 10; done; date;
              echo "Pod $host is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            name: wait-hostfilename
            volumeMounts:
            - mountPath: /etc/mpi
              name: mpi-job-config
            - mountPath: /root/.ssh
              name: ssh-auth
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
            imagePullPolicy: Always
            name: mpi-worker
            securityContext:
              privileged: true
  slotsPerWorker: 1
status:
  completionTime: "2022-01-19T16:31:06Z"
  conditions:
  - lastTransitionTime: "2022-01-19T16:30:49Z"
    lastUpdateTime: "2022-01-19T16:30:49Z"
    message: MPIJob mpi-benchmark/latency-2procs is created.
    reason: MPIJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2022-01-19T16:30:54Z"
    lastUpdateTime: "2022-01-19T16:30:54Z"
    message: MPIJob mpi-benchmark/latency-2procs is running.
    reason: MPIJobRunning
    status: "False"
    type: Running
  - lastTransitionTime: "2022-01-19T16:31:07Z"
    lastUpdateTime: "2022-01-19T16:31:07Z"
    message: MPIJob mpi-benchmark/latency-2procs successfully completed.
    reason: MPIJobSucceeded
    status: "True"
    type: Succeeded
  replicaStatuses:
    Launcher:
      succeeded: 1
    Worker: {}
  startTime: "2022-01-19T16:30:49Z"
