apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  creationTimestamp: "2022-01-19T17:55:48Z"
  generation: 1
  name: hello-4procs
  namespace: mpi-benchmark
  resourceVersion: "171177"
  uid: d4c84e25-89c4-4fd6-b679-7cca310e458e
spec:
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "4"
            - -bind-to
            - none
            - -map-by
            - slot
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - bash
            - -c
            - echo hello world
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            imagePullPolicy: Always
            name: mpi-launcher
          initContainers:
          - command:
            - bash
            - -cx
            - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile
              is ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready
              ...''; sleep 10; exit 1) && while read host; do while ! ssh $host echo
              $host ; do date; echo "Pod $host is not up ..."; sleep 10; done; date;
              echo "Pod $host is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            name: wait-hostfilename
            volumeMounts:
            - mountPath: /etc/mpi
              name: mpi-job-config
            - mountPath: /root/.ssh
              name: ssh-auth
    Worker:
      replicas: 4
      template:
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
            imagePullPolicy: Always
            name: mpi-worker
            securityContext:
              privileged: true
  slotsPerWorker: 1
status:
  completionTime: "2022-01-19T17:55:54Z"
  conditions:
  - lastTransitionTime: "2022-01-19T17:55:48Z"
    lastUpdateTime: "2022-01-19T17:55:48Z"
    message: MPIJob mpi-benchmark/hello-4procs is created.
    reason: MPIJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2022-01-19T17:55:53Z"
    lastUpdateTime: "2022-01-19T17:55:53Z"
    message: MPIJob mpi-benchmark/hello-4procs is running.
    reason: MPIJobRunning
    status: "False"
    type: Running
  - lastTransitionTime: "2022-01-19T17:55:54Z"
    lastUpdateTime: "2022-01-19T17:55:54Z"
    message: MPIJob mpi-benchmark/hello-4procs successfully completed.
    reason: MPIJobSucceeded
    status: "True"
    type: Succeeded
  replicaStatuses:
    Launcher:
      succeeded: 1
    Worker: {}
  startTime: "2022-01-19T17:55:48Z"
