apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.4.31"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.4.31"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: anyuid
    creationTimestamp: "2022-01-24T15:52:05Z"
    generateName: osu-alltoall-2procs-launcher--1-
    labels:
      controller-uid: e746e10c-bf4d-432c-ba6e-cb3adf711f41
      job-name: osu-alltoall-2procs-launcher
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: launcher
      training.kubeflow.org/operator-name: mpi-operator
    name: osu-alltoall-2procs-launcher--1-2dtm5
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: osu-alltoall-2procs-launcher
      uid: e746e10c-bf4d-432c-ba6e-cb3adf711f41
    resourceVersion: "147815"
    uid: d7d74274-79af-40b7-9042-4075175b49db
  spec:
    containers:
    - command:
      - mpirun
      - --allow-run-as-root
      - -np
      - "2"
      - -bind-to
      - none
      - -map-by
      - slot
      - -mca
      - pml
      - ob1
      - -mca
      - btl
      - ^openib
      - bash
      - -c
      - /opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/collective/osu_alltoall
      env:
      - name: K_MPI_JOB_ROLE
        value: launcher
      - name: OMPI_MCA_orte_keep_fqdn_hostnames
        value: "true"
      - name: OMPI_MCA_orte_default_hostfile
        value: /etc/mpi/hostfile
      - name: OMPI_MCA_plm_rsh_args
        value: -o ConnectionAttempts=10
      - name: OMPI_MCA_orte_set_default_slots
        value: "1"
      - name: NVIDIA_VISIBLE_DEVICES
      - name: NVIDIA_DRIVER_CAPABILITIES
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: Always
      name: mpi-launcher
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-25v5q
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-launcher
    imagePullSecrets:
    - name: default-dockercfg-nmjmb
    initContainers:
    - command:
      - bash
      - -cx
      - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile is
        ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready ...'';
        sleep 10; exit 1) && while read host; do while ! ssh $host echo $host ; do
        date; echo "Pod $host is not up ..."; sleep 10; done; date; echo "Pod $host
        is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: IfNotPresent
      name: wait-hostfilename
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-25v5q
        readOnly: true
    nodeName: ip-10-0-145-135.eu-central-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: OnFailure
    schedulerName: default-scheduler
    securityContext:
      seLinuxOptions:
        level: s0:c26,c0
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - configMap:
        defaultMode: 420
        items:
        - key: hostfile
          mode: 292
          path: hostfile
        - key: discover_hosts.sh
          mode: 365
          path: discover_hosts.sh
        name: osu-alltoall-2procs-config
      name: mpi-job-config
    - name: kube-api-access-25v5q
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:08Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:14Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:14Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:05Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://c6188633c586cc690d145c34a0287b2ec47fb6555f6d051cf1fb6768cf7a1ee3
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:4a5c4891c96005a615b162fd06c6b113816ef0fbb128489b6fc11a622f76b957
      lastState: {}
      name: mpi-launcher
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://c6188633c586cc690d145c34a0287b2ec47fb6555f6d051cf1fb6768cf7a1ee3
          exitCode: 0
          finishedAt: "2022-01-24T15:52:14Z"
          reason: Completed
          startedAt: "2022-01-24T15:52:08Z"
    hostIP: 10.0.145.135
    initContainerStatuses:
    - containerID: cri-o://1d8ef9e81d086dbb40a40b29ae46034c89c4fe4537e32bf7d6edcb6d0862d3c6
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:4a5c4891c96005a615b162fd06c6b113816ef0fbb128489b6fc11a622f76b957
      lastState: {}
      name: wait-hostfilename
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: cri-o://1d8ef9e81d086dbb40a40b29ae46034c89c4fe4537e32bf7d6edcb6d0862d3c6
          exitCode: 0
          finishedAt: "2022-01-24T15:52:07Z"
          reason: Completed
          startedAt: "2022-01-24T15:52:07Z"
    phase: Succeeded
    podIP: 10.130.4.31
    podIPs:
    - ip: 10.130.4.31
    qosClass: BestEffort
    startTime: "2022-01-24T15:52:05Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.129.10.14"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.129.10.14"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: privileged
    creationTimestamp: "2022-01-24T15:52:05Z"
    labels:
      app: osu-alltoall-2procs-worker
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "0"
    name: osu-alltoall-2procs-worker-0
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: 6cb890d3-e626-4c90-9b02-11406fcb2359
    resourceVersion: "147753"
    uid: 5b3a9511-4bc6-4a63-9f30-20fb90095e6f
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-2bgs2
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-0
    imagePullSecrets:
    - name: default-dockercfg-nmjmb
    nodeName: ip-10-0-137-230.eu-central-1.compute.internal
    nodeSelector:
      node.kubernetes.io/instance-type: c4.xlarge
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: osu-alltoall-2procs-worker
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-2bgs2
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:05Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:07Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:07Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:05Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://ac820806c2c0b04f57af10fbc1c567661331d5989d5434261cf1c710b772f5e1
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:63e1754842febbba923550c25a5f56b7240687fc37bbb9f7c05fc6bf56cb36b5
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-24T15:52:07Z"
    hostIP: 10.0.137.230
    phase: Running
    podIP: 10.129.10.14
    podIPs:
    - ip: 10.129.10.14
    qosClass: BestEffort
    startTime: "2022-01-24T15:52:05Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.131.8.18"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.131.8.18"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: privileged
    creationTimestamp: "2022-01-24T15:52:05Z"
    labels:
      app: osu-alltoall-2procs-worker
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "1"
    name: osu-alltoall-2procs-worker-1
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: 6cb890d3-e626-4c90-9b02-11406fcb2359
    resourceVersion: "147762"
    uid: 91b8505c-f839-4703-9fa6-04fcc83edfb3
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wxrqj
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-1
    imagePullSecrets:
    - name: default-dockercfg-nmjmb
    nodeName: ip-10-0-136-166.eu-central-1.compute.internal
    nodeSelector:
      node.kubernetes.io/instance-type: c4.xlarge
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: osu-alltoall-2procs-worker
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-wxrqj
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:05Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:07Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:07Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-24T15:52:05Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://08dc3db3cf0265c9bd2cffe4c5ecdb6f43f6cfb09d97711fe6e1b3446d7e658f
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:63e1754842febbba923550c25a5f56b7240687fc37bbb9f7c05fc6bf56cb36b5
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-24T15:52:07Z"
    hostIP: 10.0.136.166
    phase: Running
    podIP: 10.131.8.18
    podIPs:
    - ip: 10.131.8.18
    qosClass: BestEffort
    startTime: "2022-01-24T15:52:05Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
