apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  creationTimestamp: "2022-01-21T13:15:21Z"
  generation: 1
  name: hello-32procs
  namespace: mpi-benchmark
  resourceVersion: "105154"
  uid: 9cead83f-3f4b-4562-b777-1be8938668e8
spec:
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "32"
            - -bind-to
            - none
            - -map-by
            - slot
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - bash
            - -c
            - echo hello world
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            imagePullPolicy: Always
            name: mpi-launcher
          initContainers:
          - command:
            - bash
            - -cx
            - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile
              is ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready
              ...''; sleep 10; exit 1) && while read host; do while ! ssh $host echo
              $host ; do date; echo "Pod $host is not up ..."; sleep 10; done; date;
              echo "Pod $host is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            name: wait-hostfilename
            volumeMounts:
            - mountPath: /etc/mpi
              name: mpi-job-config
            - mountPath: /root/.ssh
              name: ssh-auth
    Worker:
      replicas: 32
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
            imagePullPolicy: Always
            name: mpi-worker
            securityContext:
              privileged: true
          nodeSelector:
            node.kubernetes.io/instance-type: m5.xlarge
  slotsPerWorker: 1
status:
  completionTime: "2022-01-21T13:15:39Z"
  conditions:
  - lastTransitionTime: "2022-01-21T13:15:21Z"
    lastUpdateTime: "2022-01-21T13:15:21Z"
    message: MPIJob mpi-benchmark/hello-32procs is created.
    reason: MPIJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2022-01-21T13:15:29Z"
    lastUpdateTime: "2022-01-21T13:15:29Z"
    message: MPIJob mpi-benchmark/hello-32procs is running.
    reason: MPIJobRunning
    status: "False"
    type: Running
  - lastTransitionTime: "2022-01-21T13:15:39Z"
    lastUpdateTime: "2022-01-21T13:15:39Z"
    message: MPIJob mpi-benchmark/hello-32procs successfully completed.
    reason: MPIJobSucceeded
    status: "True"
    type: Succeeded
  replicaStatuses:
    Launcher:
      succeeded: 1
    Worker: {}
  startTime: "2022-01-21T13:15:21Z"
