apiVersion: v1
kind: Pod
metadata:
  annotations:
    gpu-fraction: "0.250000"
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.0.168"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.129.0.168"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: runai-jupyter-notebook
    pod-group-name: pg-ssd-inference-1-c5d3ef25-be7d-4b79-abd1-7675fb602ea6
    runai-allocated-mig-gpus: "0"
    runai-calculated-status: Running
    runai-gpu: "0"
    runai-node: ip-10-0-147-203.eu-central-1.compute.internal
  creationTimestamp: "2022-03-04T12:18:55Z"
  generateName: ssd-inference-1-
  labels:
    controller-uid: c5d3ef25-be7d-4b79-abd1-7675fb602ea6
    job-name: ssd-inference-1
    matrix-benchmarking: "true"
    project: hello
    runai-pod-job-mutated: "true"
    runai/pod-index: 0-0
    user: admin
  name: ssd-inference-1-0-0
  namespace: matrix-benchmarking
  ownerReferences:
  - apiVersion: run.ai/v1
    blockOwnerDeletion: true
    controller: true
    kind: RunaiJob
    name: ssd-inference-1
    uid: c5d3ef25-be7d-4b79-abd1-7675fb602ea6
  resourceVersion: "105228"
  uid: f880812c-5e6b-43a9-87e6-1044861d51cb
spec:
  containers:
  - args:
    - |
      mkdir /tmp/cfg
      cp -v "$SRC_CONFIG_DIR"/* /tmp/cfg
      sed -i 's|/data/coco2017_tfrecords|'$STORAGE_DIR'/coco2017_tfrecords|' /tmp/cfg/*
      sed -i 's|/checkpoints|'$STORAGE_DIR'/checkpoints|' /tmp/cfg/*

      if [[ "inference" == "inference" ]]; then
        count=0
        while true; do
          bash -x examples/SSD320_FP16_inference.sh  /tmp/cfg --raport_file=/tmp/summary.json
          count=$(($count + 1))
          echo "INFERENCE_LOOP_COUNT=$count"
        done
      else
        RESULTS_DIR=/tmp/results
        mkdir "$RESULTS_DIR"
        bash -x examples/SSD320_FP16_inference.sh  "$RESULTS_DIR" /tmp/cfg --raport_file=/tmp/summary.json
      fi
    command:
    - bash
    - -ceuxo
    - pipefail
    env:
    - name: SRC_CONFIG_DIR
      value: /workdir/models/research/configs/
    - name: STORAGE_DIR
      value: /storage
    - name: reporterGatewayURL
      value: runai-prometheus-pushgateway.runai.svc.cluster.local:9091
    - name: REPORTER_GATEWAY_URL
      value: runai-prometheus-pushgateway.runai.svc.cluster.local:9091
    - name: podUUID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: POD_UUID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: POD_INDEX
      value: "0"
    - name: jobUUID
      value: c5d3ef25-be7d-4b79-abd1-7675fb602ea6
    - name: JOB_UUID
      value: c5d3ef25-be7d-4b79-abd1-7675fb602ea6
    - name: jobName
      value: ssd-inference-1
    - name: JOB_NAME
      value: ssd-inference-1
    - name: NVIDIA_VISIBLE_DEVICES
      valueFrom:
        configMapKeyRef:
          key: RUNAI-VISIBLE-DEVICES
          name: ssd-inference-1-5ngl2mx-runai-sh-gpu
    - name: RUNAI_NUM_OF_GPUS
      valueFrom:
        configMapKeyRef:
          key: RUNAI_NUM_OF_GPUS
          name: ssd-inference-1-5ngl2mx-runai-sh-gpu
    image: quay.io/openshift-psap/nvidiadl-ssd-training-benchmark:ssd
    imagePullPolicy: Always
    name: ctr
    resources:
      requests:
        cpu: 250m
        memory: "26214400"
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /storage/
      name: storage-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qztt2
      readOnly: true
    - mountPath: /runai/shared
      name: runai-shared-directory
      readOnly: true
    - mountPath: /etc/ld.so.preload
      name: ssd-inference-1-5ngl2mx-runai-sh-gpu-vol
      readOnly: true
      subPath: ld.so.preload-key
    - mountPath: /etc/runai.d/memory
      name: ssd-inference-1-5ngl2mx-runai-sh-gpu-vol
      readOnly: true
      subPath: config
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-h4wcb
  nodeName: ip-10-0-147-203.eu-central-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: runai-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c26,c10
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: benchmarking-coco-dataset
  - name: kube-api-access-qztt2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
  - hostPath:
      path: /var/lib/runai/shared
      type: DirectoryOrCreate
    name: runai-shared-directory
  - configMap:
      defaultMode: 420
      name: ssd-inference-1-5ngl2mx-runai-sh-gpu
    name: ssd-inference-1-5ngl2mx-runai-sh-gpu-vol
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-04T12:18:56Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-04T12:19:06Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-04T12:19:06Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-04T12:18:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://7a7a9620ad5b911ff786b77b599383add0a9228260dae00f90799386cf9a4868
    image: quay.io/openshift-psap/nvidiadl-ssd-training-benchmark:ssd
    imageID: quay.io/openshift-psap/nvidiadl-ssd-training-benchmark@sha256:0177e9f4174b98ed1b79a952b2bdf60be6c0a1d7d534b46e6f34a6012db4e52f
    lastState: {}
    name: ctr
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-04T12:19:05Z"
  hostIP: 10.0.147.203
  phase: Running
  podIP: 10.129.0.168
  podIPs:
  - ip: 10.129.0.168
  qosClass: Burstable
  startTime: "2022-03-04T12:18:56Z"
