apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.232"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.232"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: anyuid
    creationTimestamp: "2022-01-19T16:36:41Z"
    generateName: osu-alltoall-2procs-launcher--1-
    labels:
      controller-uid: 95fea0f7-245c-43c4-b8e9-999b22b9d07a
      job-name: osu-alltoall-2procs-launcher
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: launcher
      training.kubeflow.org/operator-name: mpi-operator
    name: osu-alltoall-2procs-launcher--1-5mltx
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: osu-alltoall-2procs-launcher
      uid: 95fea0f7-245c-43c4-b8e9-999b22b9d07a
    resourceVersion: "132499"
    uid: f73ee637-4c43-4cb1-8485-cb628019a196
  spec:
    containers:
    - command:
      - mpirun
      - --allow-run-as-root
      - -np
      - "2"
      - -bind-to
      - none
      - -map-by
      - slot
      - -mca
      - pml
      - ob1
      - -mca
      - btl
      - ^openib
      - bash
      - -c
      - /opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/collective/osu_alltoall
      env:
      - name: K_MPI_JOB_ROLE
        value: launcher
      - name: OMPI_MCA_orte_keep_fqdn_hostnames
        value: "true"
      - name: OMPI_MCA_orte_default_hostfile
        value: /etc/mpi/hostfile
      - name: OMPI_MCA_plm_rsh_args
        value: -o ConnectionAttempts=10
      - name: OMPI_MCA_orte_set_default_slots
        value: "1"
      - name: NVIDIA_VISIBLE_DEVICES
      - name: NVIDIA_DRIVER_CAPABILITIES
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: Always
      name: mpi-launcher
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-l2rh9
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-launcher
    imagePullSecrets:
    - name: default-dockercfg-9grqg
    initContainers:
    - command:
      - bash
      - -cx
      - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile is
        ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready ...'';
        sleep 10; exit 1) && while read host; do while ! ssh $host echo $host ; do
        date; echo "Pod $host is not up ..."; sleep 10; done; date; echo "Pod $host
        is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imagePullPolicy: IfNotPresent
      name: wait-hostfilename
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/mpi
        name: mpi-job-config
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-l2rh9
        readOnly: true
    nodeName: ip-10-0-158-149.eu-central-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: OnFailure
    schedulerName: default-scheduler
    securityContext:
      seLinuxOptions:
        level: s0:c26,c5
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - configMap:
        defaultMode: 420
        items:
        - key: hostfile
          mode: 292
          path: hostfile
        - key: discover_hosts.sh
          mode: 365
          path: discover_hosts.sh
        name: osu-alltoall-2procs-config
      name: mpi-job-config
    - name: kube-api-access-l2rh9
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:44Z"
      reason: PodCompleted
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:48Z"
      reason: PodCompleted
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:48Z"
      reason: PodCompleted
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:41Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://8f9c636dfe125d1cd69fc173dedf022b3aec67dde8b5f4450833e60fcece11fd
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:57894edcb555f32c3f6ce898db35799c869222cc0c00690c8347fd38c66442ea
      lastState: {}
      name: mpi-launcher
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: cri-o://8f9c636dfe125d1cd69fc173dedf022b3aec67dde8b5f4450833e60fcece11fd
          exitCode: 0
          finishedAt: "2022-01-19T16:36:48Z"
          reason: Completed
          startedAt: "2022-01-19T16:36:45Z"
    hostIP: 10.0.158.149
    initContainerStatuses:
    - containerID: cri-o://a54413c4f8e4e7adf2258cf65e7e21f2dd23e6e64067c7db9497236b956debb4
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:57894edcb555f32c3f6ce898db35799c869222cc0c00690c8347fd38c66442ea
      lastState: {}
      name: wait-hostfilename
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: cri-o://a54413c4f8e4e7adf2258cf65e7e21f2dd23e6e64067c7db9497236b956debb4
          exitCode: 0
          finishedAt: "2022-01-19T16:36:44Z"
          reason: Completed
          startedAt: "2022-01-19T16:36:44Z"
    phase: Succeeded
    podIP: 10.130.0.232
    podIPs:
    - ip: 10.130.0.232
    qosClass: BestEffort
    startTime: "2022-01-19T16:36:41Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.230"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.230"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-01-19T16:36:41Z"
    labels:
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "0"
    name: osu-alltoall-2procs-worker-0
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: 71c7c87b-439c-42d0-824a-53f6fe26e93c
    resourceVersion: "132457"
    uid: 92f23047-4227-41b0-86e0-fc1086fb25fb
  spec:
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-9b68x
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-0
    imagePullSecrets:
    - name: default-dockercfg-9grqg
    nodeName: ip-10-0-158-149.eu-central-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-9b68x
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:41Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:43Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:43Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:41Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://ae509b9a45dfebd60a1d452a19aa3fdeee84bc4f412bebdbf19ccd0299d4e3bd
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:39b127a3747ed7ee1781adaeefbac1b0c3c7d8dadaa4c8e9ced54a9bf3f419ff
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-19T16:36:43Z"
    hostIP: 10.0.158.149
    phase: Running
    podIP: 10.130.0.230
    podIPs:
    - ip: 10.130.0.230
    qosClass: BestEffort
    startTime: "2022-01-19T16:36:41Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.231"
            ],
            "default": true,
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "openshift-sdn",
            "interface": "eth0",
            "ips": [
                "10.130.0.231"
            ],
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: node-exporter
    creationTimestamp: "2022-01-19T16:36:41Z"
    labels:
      training.kubeflow.org/job-name: osu-alltoall-2procs
      training.kubeflow.org/job-role: worker
      training.kubeflow.org/operator-name: mpi-operator
      training.kubeflow.org/replica-index: "1"
    name: osu-alltoall-2procs-worker-1
    namespace: mpi-benchmark
    ownerReferences:
    - apiVersion: kubeflow.org/v2beta1
      blockOwnerDeletion: true
      controller: true
      kind: MPIJob
      name: osu-alltoall-2procs
      uid: 71c7c87b-439c-42d0-824a-53f6fe26e93c
    resourceVersion: "132476"
    uid: 3d1a7122-b7fb-48c0-95f8-73196e86f372
  spec:
    containers:
    - command:
      - /usr/sbin/sshd
      - -De
      env:
      - name: K_MPI_JOB_ROLE
        value: worker
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imagePullPolicy: Always
      name: mpi-worker
      resources: {}
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-auth
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-97c5v
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    hostname: osu-alltoall-2procs-worker-1
    imagePullSecrets:
    - name: default-dockercfg-9grqg
    nodeName: ip-10-0-158-149.eu-central-1.compute.internal
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    subdomain: osu-alltoall-2procs-worker
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: ssh-auth
      secret:
        defaultMode: 384
        items:
        - key: ssh-privatekey
          path: id_rsa
        - key: ssh-publickey
          path: id_rsa.pub
        - key: ssh-publickey
          path: authorized_keys
        secretName: osu-alltoall-2procs-ssh
    - name: kube-api-access-97c5v
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:41Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:44Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:44Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-01-19T16:36:41Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://56eb9308ef7a38b9f76e2fc91a64faec712bf3cf71cee153f0890e43aebe9d1b
      image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
      imageID: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench@sha256:39b127a3747ed7ee1781adaeefbac1b0c3c7d8dadaa4c8e9ced54a9bf3f419ff
      lastState: {}
      name: mpi-worker
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-01-19T16:36:44Z"
    hostIP: 10.0.158.149
    phase: Running
    podIP: 10.130.0.231
    podIPs:
    - ip: 10.130.0.231
    qosClass: BestEffort
    startTime: "2022-01-19T16:36:41Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
