apiVersion: run.ai/v1
kind: RunaiJob
metadata:
  annotations:
    runai-calculated-status: Succeeded
    runai-current-allocated-gpus: "0.000"
    runai-current-allocated-gpus-memory: "0"
    runai-current-requested-gpus: "0.000"
    runai-current-requested-gpus-memory: "0"
    runai-pending-pods: "0"
    runai-podgroup-requested-gpus: "0.750"
    runai-podgroup-requested-gpus-memory: "0"
    runai-running-pods: "0"
    runai-total-requested-gpus: "0.750"
    runai-total-requested-gpus-memory: "0"
    runai-used-nodes: '-'
  creationTimestamp: "2022-03-04T13:25:58Z"
  generation: 1
  labels:
    matrix-benchmarking: "true"
    matrix-benchmarking-mode: training
    priorityClassName: build
    project: hello
  name: ssd-training-1
  namespace: matrix-benchmarking
  resourceVersion: "133664"
  uid: 0daf3e38-3ea1-4426-ae86-e986c1d23e26
spec:
  template:
    metadata:
      annotations:
        gpu-fraction: "0.750000"
      labels:
        job-name: ssd-training-1
        matrix-benchmarking: "true"
        project: hello
        user: admin
    spec:
      containers:
      - args:
        - |
          mkdir /tmp/cfg
          cp -v "$SRC_CONFIG_DIR"/* /tmp/cfg
          sed -i 's|/data/coco2017_tfrecords|'$STORAGE_DIR'/coco2017_tfrecords|' /tmp/cfg/*
          sed -i 's|/checkpoints|'$STORAGE_DIR'/checkpoints|' /tmp/cfg/*

          if [[ "training" == "inference" ]]; then
            count=0
            while true; do
              bash -x examples/SSD320_FP16_1GPU_BENCHMARK.sh /tmp/cfg --raport_file=/tmp/summary.json
              count=$(($count + 1))
              echo "INFERENCE_LOOP_COUNT=$count"
            done
          else
            RESULTS_DIR=/tmp/results
            mkdir "$RESULTS_DIR"
            bash -x examples/SSD320_FP16_1GPU_BENCHMARK.sh "$RESULTS_DIR" /tmp/cfg --raport_file=/tmp/summary.json
          fi
        command:
        - bash
        - -ceuxo
        - pipefail
        env:
        - name: SRC_CONFIG_DIR
          value: /workdir/models/research/configs/
        - name: STORAGE_DIR
          value: /storage
        - name: reporterGatewayURL
          value: runai-prometheus-pushgateway.runai.svc.cluster.local:9091
        - name: REPORTER_GATEWAY_URL
          value: runai-prometheus-pushgateway.runai.svc.cluster.local:9091
        - name: podUUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/openshift-psap/nvidiadl-ssd-training-benchmark:ssd
        imagePullPolicy: Always
        name: ctr
        resources:
          limits: {}
          requests:
            cpu: 750m
            memory: "78643200"
        volumeMounts:
        - mountPath: /storage/
          name: storage-volume
      restartPolicy: Never
      schedulerName: runai-scheduler
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: benchmarking-coco-dataset
status:
  completionTime: "2022-03-04T13:43:13Z"
  conditions:
  - lastProbeTime: "2022-03-04T13:43:13Z"
    lastTransitionTime: "2022-03-04T13:43:13Z"
    status: "True"
    type: Complete
  startTime: "2022-03-04T13:25:58Z"
  succeeded: 1
