apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  creationTimestamp: "2022-01-25T09:59:23Z"
  generation: 1
  name: osu-allreduce-24procs
  namespace: mpi-benchmark
  resourceVersion: "93822"
  uid: 9d5f5214-8870-495a-8d89-4ca388a2fd02
spec:
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "24"
            - -bind-to
            - none
            - -map-by
            - slot
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - bash
            - -c
            - /opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi/collective/osu_allreduce
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            imagePullPolicy: Always
            name: mpi-launcher
          initContainers:
          - command:
            - bash
            - -cx
            - '[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo ''Hostfile
              is ready''; cat /etc/mpi/hostfile) || (date; echo ''Hostfile not ready
              ...''; sleep 10; exit 1) && while read host; do while ! ssh $host echo
              $host ; do date; echo "Pod $host is not up ..."; sleep 10; done; date;
              echo "Pod $host is ready"; done <<< "$(cat /etc/mpi/hostfile)"'
            image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:base
            name: wait-hostfilename
            volumeMounts:
            - mountPath: /etc/mpi
              name: mpi-job-config
            - mountPath: /root/.ssh
              name: ssh-auth
    Worker:
      replicas: 24
      template:
        metadata:
          labels:
            app: osu-allreduce-24procs-worker
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/mpi-benchmark/mpi-bench:osu-bench
            imagePullPolicy: Always
            name: mpi-worker
            securityContext:
              privileged: true
          nodeSelector:
            node.kubernetes.io/instance-type: c4.xlarge
          topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                app: osu-allreduce-24procs-worker
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
  slotsPerWorker: 1
status:
  completionTime: "2022-01-25T10:00:01Z"
  conditions:
  - lastTransitionTime: "2022-01-25T09:59:23Z"
    lastUpdateTime: "2022-01-25T09:59:23Z"
    message: MPIJob mpi-benchmark/osu-allreduce-24procs is created.
    reason: MPIJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2022-01-25T09:59:31Z"
    lastUpdateTime: "2022-01-25T09:59:31Z"
    message: MPIJob mpi-benchmark/osu-allreduce-24procs is running.
    reason: MPIJobRunning
    status: "False"
    type: Running
  - lastTransitionTime: "2022-01-25T10:00:02Z"
    lastUpdateTime: "2022-01-25T10:00:02Z"
    message: MPIJob mpi-benchmark/osu-allreduce-24procs successfully completed.
    reason: MPIJobSucceeded
    status: "True"
    type: Succeeded
  replicaStatuses:
    Launcher:
      succeeded: 1
    Worker: {}
  startTime: "2022-01-25T09:59:23Z"
